### ISSUE TITLE
Non-Responsive when opening a type

### ISSUE THREAD

**Issue by FrederoxDev** [ergrelet/resym#46]
![image](https://github.com/ergrelet/resym/assets/69014593/8394c401-155f-4485-90a3-287e22bfd053)

When trying to open a type, the console is spammed with messages and the program becomes non responsive. 
It works fine for another person using the program, but not for me

**Comment by ergrelet** [comment]
Hi!

It could be that you're trying to display a type with a huge amount of dependencies?
Unfortunately, as stated in the README, for huge outputs, the GUI gets a little bit slow at the moment:
> The GUI version might struggle to display huge outputs (>20 MB). Disabling syntax highlighting (or dependency reconstruction altogether) will help, but generally the CLI version is more suited when dumping types with a huge amount of dependencies.

Try going into settings and disabling "Print definitions of referenced types". Maybe that's why the other person is able to load this type.

**Comment by FrederoxDev** [comment]
Ah yeah disabling that setting works for me to see that type
